### ISSUE TITLE
[EKF] Parameter  `imuN` contains and uses fields for x,y,z, vx,vy,vz

### ISSUE THREAD

**Issue by johuber** [cra-ros-pkg/robot_localization#432] opened 2018-11-30 10:41 UTC
The fields for `x,y,z, vx,vy,vz` in the parameter `imuN` first of all make no sense, because an Imu message does not contain these; even worse though, they are actually used by the filter.
Hence, if somebody was to set the field of `vx` to `true` the filter will accept this and introduce a velocity measurement of value 0.0 with 0.0 covariance, which is highly undesired.

The parameters should either be removed or at least it should be ensured, that `true` entries of non-existing data does not have an impact.

**Comment by ayrton04** [comment] 2018-11-30 11:20
The parameter specification is uniform to avoid confusion, though I realize it can have the opposite effect. In any case, I don't think changing the parameter specification at this stage in the package's life cycle is a good idea.

The issue is easily fixed by a small change to the IMU configuration loading. We just need to mask off the `X, Y, Z` and `vX, vY, vZ` variables when we load the IMU config here:

https://github.com/cra-ros-pkg/robot_localization/blob/81f7d9b4f88165567ef433c7ca75cb6042fa46c1/src/ros_filter.cpp#L1309-L1333

We could also add a warning if the user makes an invalid specification for a given sensor type, if that would help.

Care to submit a PR?

**Comment by johuber** [comment] 2018-11-30 13:26
> The parameter specification is uniform to avoid confusion, though I realize it can have the opposite effect. In any case, I don't think changing the parameter specification at this stage in the package's life cycle is a good idea.

I see that, that's also ok like this.

The suggested change looks very reasonable. However, I currently don't have capacity to do it myself.

**Closed as completed** 2019-11-26 12:33 UTC
