### ISSUE TITLE
Manual Datum Does not support setting gps frame, so it is ""

### ISSUE THREAD

**Issue by bcfjohns** [cra-ros-pkg/robot_localization#298] opened 2016-06-29 16:44 UTC
The manual datum topic allows setting of the base link and world frames, but not the gps frame, so when the  node is used with only a manual datum, the gps frame is "". This means the node constantly sends warnings and then publishes odometery information as all zeros. That's with version 2.2.3 in Indigo.

**Comment by ayrton04** [comment] 2016-06-30 09:59
Thanks! Any chance you'd be willing to take a crack at a PR?

**Comment by bcfjohns** [comment] 2016-07-08 20:51
Unfortunately, not anytime soon.

**Comment by skohlbr** [comment] 2016-07-12 09:14
+1, just ran into this also. For setting datum manually, adding a frame_id as param seems possible. Or should we wait for first fix data and then use that? There are a few options of adding this, but they have some subtle differences. Setting via the service should also work correctly.

**Comment by ayrton04** [comment] 2016-07-12 09:26
Can you try this fork and let me know if it's fixed?

https://github.com/locusrobotics/robot_localization

I plan to merge upstream. Part of the problem is that I'd have to add another parameter to the datum to fix this issue, and after some consideration, it seems that I ought to still use the frame_ids from the input messages, rather than forcing users to add them to the datum. What do you think?

**Comment by ayrton04** [comment] 2016-07-15 09:06
Has anyone had a chance to try this?

**Comment by ayrton04** [comment] 2016-08-01 10:47
@bcfjohns @skohlbr I think I've addressed this, but I'd have to see how it works for you. I had to change the datum parameter behavior so that it doesn't concern itself with frame_ids; those are now assumed to come from the input messages, even if the datum is specified.

**Comment by ayrton04** [comment] 2016-09-07 07:54
Closing this. Feel free to reopen if it's still a problem.

**Closed as completed by ayrton04** 2016-09-07 07:54 UTC
